# UNIFORM PLAYER CONTRACT

## Required Form.

The Player Contract to be entered into by each player and the Team by which he is employed shall be a Uniform Player Contract in the form annexed hereto as Exhibit A.

## Limitation on Amendments.

(a) Except as provided in Sections 3, 8, and 9 of this Article, no amendments to the form of Uniform Player Contract provided for by Section 1 of this Article shall be permitted.
(b) If a Team and a player enter into (i) a Uniform Player Contract containing an amendment not specifically permitted by this Agreement or (ii) a subsequent amendment to an existing Player Contract where such amendment is not specifically permitted by this Agreement, then such Contract or subsequent amendment, as the case may be, shall be disapproved by the Commissioner and, consequently, rendered null and void.

## Allowable Amendments.

In their individual contract negotiations, a player and a Team may amend the provisions of a Uniform Player Contract, but only in the following respects:

(a) By agreeing upon provisions (to be set forth in Exhibit 1 to a Uniform Player Contract) with respect to the Cash Compensation to be paid or amounts to be loaned to the player for rendering the services described in such Contract.
(b) By agreeing upon provisions (to be set forth in Exhibit 1 to a Uniform Player Contract) with respect to any form of Non-Cash Compensation to be paid or provided to the player for rendering the services described in such Contract.
(c) By agreeing upon provisions (to be set forth in Exhibit 1 to a Uniform Player Contract) with respect to bonuses, or increases or reductions in Cash Compensation, for (i) the player's execution of a Uniform Player Contract (a "signing bonus"), (ii) the exercise or non-exercise of an option pursuant to Articles VII and XII, (iii) the player's achievement (in the case of a bonus or increase in Cash Compensation) of agreed-upon benchmarks relating to his performance as a player, (iv) the player's achievement (in the case of a bonus or increase in Cash Compensation) or non-achievement (in the case of a reduction in Cash Compensation) of agreed-upon benchmarks relating to his physical condition or academic achievement, or (v) the Team's performance during a particular NBA Season (in the case of a bonus or increase in Cash Compensation), subject to the limitations imposed by paragraph 3(c) of the Uniform Player Contract. Any amendment agreed upon pursuant to subsections (c)(iii), (iv), or (v) above must be structured so as to provide an incentive for positive achievement by the player (under (c) (iii) and (iv)) and the Team (under (c)(v)).
(d) By agreeing upon a Salary payment schedule (to be set forth in Exhibit 1 to a Uniform Player Contract) different from that provided for by paragraph 3(a) of the prescribed form of Uniform Player Contract; provided, however, that, if the Salary to be paid for the Season with respect to which such payment schedule applies is not greater than the Minimum Annual Salary called for with respect to that Season pursuant to Article II, Section 6, such different payment schedule shall be more favorable to the player than that provided for by paragraph 3(a) of the prescribed form of Uniform Player Contract.
(e) By agreeing upon provisions (to be set forth in Exhibit 2 to a Uniform Player Contract) that the Cash Compensation provided for by a Uniform Player Contract (as described in Exhibit 1 to such Contract) shall be, in whole or in part, and subject to any conditions or limitations, protected or insured (as provided for by, and in accordance with the definitions set forth in, Section 4 of this Article) in the event that such Contract is terminated by the Team by reason of the player's:
    (i) lack of skill;
    (ii) personal conduct;
    (iii) death not covered by an insurance policy procured by a Team for the player's benefit ("non-insured death");
    (iv) death covered by an insurance policy procured by a Team for the player's benefit ("insured death");
    (v) disability or unfitness to play skilled basketball resulting from a basketball-related injury not covered by an insurance policy procured by a Team for the player's benefit ("non-insured basketball-related injury");
    (vi) disability or unfitness to play skilled basketball resulting from any injury or illness not covered by an insurance policy procured by a Team for the player's benefit ("non-insured injury or illness");
    (vii) disability or unfitness to play skilled basketball resulting from an injury or illness covered by an insurance policy procured by a Team for the player's benefit ("insured injury or illness");
    (viii) mental disability not covered by an insurance policy procured by a Team for the player's benefit ("non-insured mental disability"); and/or
    (ix) mental disability covered by an insurance policy procured by a Team for the player's benefit ("insured mental disability").(f) By agreeing upon a provision (to be set forth in Exhibit 3 to a Uniform Player Contract) limiting or eliminating the player's right to receive his Cash Compensation (in accordance with paragraphs 7(c) and 16(b) of the prescribed form of Uniform Player Contract) when the player's disability or unfitness to play skilled basketball is caused by the re-injury of an injury sustained prior to, or by the aggravation of a condition that existed prior to, the execution of the Uniform Player Contract providing for such Cash Compensation.
(g) By agreeing upon a provision (to be set forth in Exhibit 4 to a Uniform Player Contract) entitling a player to receive Cash Compensation upon the sale, exchange, assignment, or transfer of such player's Uniform Player Contract, subject, however, to the provisions of Article XXIV.
(h) By agreeing upon a provision (to be set forth in Exhibit 5 to a Uniform Player Contract) permitting the player to participate or engage in some or all of the activities otherwise prohibited by paragraph 12 of the prescribed form of Uniform Player Contract; provided, however, that paragraph 12 of the prescribed form of Uniform Player Contract may not be amended to permit a player to participate in any public game or public exhibition of basketball not approved in accordance with Article XXIII of this Agreement.
(i) By agreeing upon a provision (to be set forth in Exhibit 6 to a Uniform Player Contract) that conditions the validity of the Contract on the player's ability to pass, in the sole discretion of a physician designated by the Team, a physical examination conducted within forty-eight (48) hours of the execution of the Contract.
(j) By agreeing to delete clauses (b )(ii) and/or (b )(iii) of paragraph 5 of the prescribed form of Uniform Player Contract in their entirety.
(k) By agreeing to delete paragraph 7(b) of the prescribed form of Uniform Player Contract in its entirety and substituting therefor the provision set forth in Exhibit 7 to a Uniform Player Contract.
(l) By agreeing either (i) to delete paragraph 13(b) of the prescribed form of Uniform Player Contract in its entirety, or (ii) to delete the last sixteen words of paragraph 13(b) of such Contract.

## Salary Protection or Insurance.

(a) <u>**Lack of Skill.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(ii) thereof, by reason of the player's lack of skill, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 to the Uniform Player Contract, notwithstanding the provisions of paragraphs 16(a)(ii), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team on account of the player's failure to exhibit sufficient skill or competitive ability shall in no way affect the player's right to receive the Cash Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit.
(b) <u>**Personal Conduct.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(i) thereof, by reason of the player's personal conduct, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 to the Uniform Player Contract, notwithstanding the provisions of paragraphs 16(a)(i), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team on account of the player's failure, refusal or neglect to conform his personal conduct to standards of good citizenship and/or the player's failure, refusal or neglect to conform his personal conduct to standards of good sportsmanship and/or the player's failure, refusal or neglect to obey the Team's training rules shall in no way affect the player's right to receive the Cash Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit.
(c) <u>**Non-Insured Death.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iii) thereof, by reason of the player's non-insured death, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 to the Uniform Player Contract, notwithstanding the provisions of paragraphs 16(a), 16(b), 16(c), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team on account of the player's failure to render his services thereunder, if such failure has been caused by the player's death, shall in no way affect the player's (or his estate's or duly appointed beneficiary's) right to receive the Cash Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that (i) such death does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified by Exhibit 5 to the Player Contract), suicide, the abuse of alcohol, or the use of any controlled substance; (ii) at the time of the player's failure to render playing services, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's death, the player cooperates with the Team in procuring such an insurance policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player (and/or his estate and/or duly appointed beneficiary) cooperates with the Team and insurance company in the processing of the Team's claim under such policy.
(d) <u>**Insured Death.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iii) thereof, by reason of the player's insured death, such agreement shall mean that, subject to any conditions set forth in Exhibit 2 and/or Exhibit 3 to the Uniform Player Contract, the Team has procured (or will procure forth-with) an insurance policy (specifically designated in Exhibit 2 to such Contract) for the benefit of the player Of his estate or beneficiary that, subject to the conditions and limitations contained in the policy, would pay a benefit in the event of the player's death in an amount equal to or less than the Cash Compensation remaining to be paid to the player under Exhibit 1 of his Player Contract at the time of his death; provided, however, that (i) such death does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified by Exhibit 5 to the Player Contract), suicide, the abuse of alcohol, or the use of any controlled substance; and (ii) at the time of the player's failure to render playing services, the player is not in material breach of such Contract.
(e) <u>**Non-Insured Basketball-Related Injury.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraphs 7(c), 16(b), and/or 16(c) thereof, by reason of the player's disability or unfitness to play skilled basketball resulting from a non-insured basketball-related injury, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 and/or Exhibit 3 to the Uniform Player Contract, notwithstanding the provisions of paragraphs 7(b), 7(c), 16(a)(iii), 16(b), 16(c), 16(d), and 16(g) of such Contract, the termination of such Contract by the Team because the player has been disabled and/or is unfit to play skilled basketball as a direct result of an injury sustained while participating in any basketball practice or game played for the Team shall in no way affect the player's right to receive the Cash Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that (i) such injury does not result from an attempted suicide or the use of any controlled substance; (ii) at the time of the player's termination, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's injury, the player cooperates with the Team in procuring such an insurance policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player cooperates with the Team and the insurance company in the processing of the Team's claim under such policy.
(f) <u>**Non-Insured Injury or Illness.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such contract is terminated by the Team, pursuant to paragraphs 7 (c), 16(b) and/or 16(c) thereof, by reason of the player's disability or unfitness to play skilled basketball resulting from any non-insured injury or illness, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 and/or Exhibit 3 to the Uniform Player Contract, notwithstanding the provisions of paragraphs 7(b), 7(c), 16(a)(iii), 16(b), 16(c), 16(d), and 16(g) of such Contract, the termination of such Contract by the Team on account of an injury, illness, or disability suffered or sustained by the player shall in no way affect the player's right to receive the Cash Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that (i) such injury, illness, or disability does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified in Exhibit 5 to the Player Contract), attempted suicide, the abuse of alcohol, or the use of any controlled substance; (ii) at the time of such injury, illness, or disability the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's injury and/or illness, the player cooperates with the Team in procuring such an insurance policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player cooperates with the Team and insurance company in the processing of the Team's claim under such policy.
(g) <u>**Insured Injury or Illness.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraphs 7(c), 16(b) and/or 16(c) thereof, by reason of the player's disability or unfitness to play skilled basketball resulting from an insured injury or illness, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 and/or Exhibit 3 to the Uniform Player Contract, the Team has procured (or will procure forthwith) an insurance policy (specifically designated in Exhibit 2 to such Contract) for the benefit of the player or his estate or beneficiary that, subject to the conditions and limitations contained in the policy, would pay a benefit in the event of the player's disability or unfitness to play skilled basketball resulting from an injury or illness in an amount equal to or less than the Cash Compensation remaining to be paid to the player under Exhibit 1 of his Player Contract at the time of his termination; provided, however, that (i) such injury or illness does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified by Exhibit 5 to the Player Contract), attempted suicide, the abuse of alcohol, or the use of any controlled substance; and (ii) at the time of the player's termination, the player is not in material breach of such Contract.
(h) <u>**Non-Insured Mental Disability.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iii) thereof, by reason of the player's non-insured mental disability, such agreement shall mean that, subject to any conditions or limitations set forth in Exhibit 2 and/or Exhibit 3 to the Uniform Player Contract, notwithstanding the provisions of paragraphs 16(a), 16(b), 16(c), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team on account of the player's failure to render his services thereunder, if such failure has been caused by the player's mental disability, shall in no way affect the player's (or his duly appointed legal representative's) right to receive the Cash Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that (i) such mental disability does not result from the player's attempted suicide or the use of any controlled substance; (ii) at the time of the player's failure to render playing services, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's mental disability, the player (and/or his duly appointed legal representative) cooperates with the Team in procuring such an insurance policy; and (iv) if the Team, for its own benefit, has procured an insurance policy covering the player's mental disability, the player (and/or his duly appointed legal representative) cooperates with the Team and insurance company in the processing of the Team's claim under such policy.
(i) <u>**Insured Mental Disability.**</u> When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iii) thereof, by reason of the player's insured mental disability, such agreement shall mean that, subject to any conditions set forth in Exhibit 2 and/or Exhibit 3 to the Uniform Player Contract, the Team has procured (or will procure forthwith) an insurance policy (specifically designated in Exhibit 2 to such Contract) for the benefit of the player or his estate or beneficiary that, subject to the conditions and limitations contained in the policy, would pay a benefit in the event of the player's mental disability in an amount equal to or less than the Cash Compensation remaining to be paid to the player under Exhibit 1 of his Player Contract at the time of his termination; provided, however, that (i) such mental disability does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified by Exhibit 5 to the Player Contract), attempted suicide or the use of any controlled substance; and (ii) at the time of the player's termination, the player is not in material breach of such Contract.
(j) No agreement by a Team to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract shall require (or be construed as requiring) such Team to continue the player on the Team, Active List, or Roster; nor shall any such agreement afford the player any right to continue, or to be deemed as having continued, on such Team, Active List, or Roster for any purpose.
(k) When a Team agrees to protect, in whole or in part, the Cash Compensation provided for by a Uniform Player Contract, and such protection is contingent on the satisfaction of a condition expressly set forth in Exhibit 2 to that Contract, such protection shall be applicable and effective only if the Player Contract has not previously been terminated at the time such condition is satisfied.
(l) When a Team agrees to protect, in whole or in part, the Cash Compensation provided for in any option year (in favor of the team or the player) included in a Uniform Player Contract, such protection shall be applicable and effective only if the option to extend the term provided for in the Contract is exercised.

## Conformity.

All currently effective Player Contracts, and all Player Contracts entered into following the execution of this Agreement that do not otherwise so provide, shall be deemed amended in such manner to require the parties to comply with all terms of this Agreement, including the terms of the Uniform Player Contract annexed hereto as Exhibit A. All Player Contracts shall be subject to the terms of this Agreement, which shall supersede the terms of any Player Contract inconsistent herewith. No Player Contract shall provide for the waiver by a player or a Team of any benefits or the sacrifice of any rights to which the player or the Team is entitled by virtue of a Uniform Player Contract or this Agreement.

## Minimum Annual Salary.

(a) Except with respect to Ten-Day Contracts provided for in Article II, Section 8, and Rest-of-Season Contracts provided for in Article II, Section 9, no Player Contract shall provide for a Salary of less than the following:
    (i) For the 1995-96 Season: \$225,000
    (ii) For the 1996-97 Season: \$247,500
    (iii) For the 1997-98 through 2000-01 Seasons:
        (A) Prior to the issuance of the Audit Report for the prior Season, the Minimum Annual Salary shall be the Minimum Annual Salary for the prior Season increased by ten percent (10\%).
        (B) Following the issuance of the Audit Report for the prior Season, the Minimum Annual Salary shall be the Minimum Annual Salary for the prior Season increased by the greater of ten percent (10\%) or the percentage by which BRI for the prior Season increased over BRI for the Season immediately preceding such prior Season. Once the Audit Report for the prior Season is issued, any Player Contract that provides for the Minimum Annual Salary calculated pursuant to subsection (A) above shall be deemed amended to provide for the Minimum Annual Salary calculated pursuant to this subsection (B).
(b) Notwithstanding the provisions of Section 6(a) of this Article, no Player Contract between a Team and a player selected in the second round of the NBA Draft, or between a Team and a player not selected in the NBA Draft for which he is first eligible, shall provide, with respect to the player's first NBA Season, for a Salary of less than the following:
    (i) For the 1995-96 Season: \$200,000
    (ii) For the 1996-97 Season: \$220,000
    (iii) For the 1997-98 through 2000-01 Seasons:
        (A) Prior to the issuance of the Audit Report for the prior Season, the Minimum Annual Salary shall be the Minimum Annual Salary for the prior Season increased by ten percent (10\%).
        (B) Following the issuance of the Audit Report for the prior Season, the Minimum Annual Salary shall be the Minimum Annual Salary for the prior Season increased by the greater of ten percent (10\%) or the percentage by which BRI for the prior Season increased over BRI for the Season immediately preceding such prior Season. Once the Audit Report for the prior Season is issued, any Player Contract that provides for the Minimum Annual Salary calculated pursuant to subsection (A) above shall be deemed amended to provide for the Minimum Annual Salary calculated pursuant to this subsection (B).
(c) In determining whether a Player Contract satisfies the Minimum Annual Salary requirements established by this Section, the allocation of signing bonuses, deemed signing bonuses (pursuant to Article VII, Section 3(b », and other bonuses not contingent upon a player's or a Team's attaining a particular level of performance shall be considered as part of the Salary provided for by a Player Contract, provided that such Player Contract makes clear that the Salary for each Season (including bonuses) equals or exceeds the Minimum Annual Salary for such Season.
(d) Nothing in this Section shall alter the respective rights and liabilities of a player and a Team, as provided for in the Uniform Player Contract or in this Agreement, with respect to the termination of a Player Contract.

## Promotional Activities.

(a) A player may not enter into any contract or other commercial arrangement to perform any of the promotional activities set forth in paragraph 13(b) of the Uniform Player Contract (regardless of whether, in connection with such activities, the player is in any way identified with the Team) on behalf of an entity or person that offers a product or service that competes in the same product or service category as the products or services of a Protected Team Sponsor (as defined in subsection (i) below). The designation of Protected Team Sponsors shall be governed by the following:
    (i) Prior to each NBA Season during the term of this Agreement, a Team may designate no more than two (2) sponsors of the Team that it seeks to protect against conflicting commercial or promotional activities in the Team's local marketing area involving that Team's players ("Protected Team Sponsors"). The designation of a sponsor as a Protected Team Sponsor shall last for one year, from September 1 to the next August 31.
    (ii) If a Team chooses to designate Protected Team Sponsor(s), the Team must notify its players of such designation, and of the product or service categories in which its Protected Team Sponsor(s) compete, on or before the September 1 immediately preceding the year in which the Protected Team Sponsor designation will apply.
    (iii) A Team may not designate a sponsor as a Protected Team Sponsor unless the sponsor conducts business in a product or service category set forth in Exhibit E to this Agreement. Local automobile dealerships and retail shoe outlets shall not be designated as Protected Team Sponsors. Nothing in this Section 7(a) shall prohibit a player from entering into a contract or other commercial arrangement to perform national promotional activities on behalf of an entity or person that conducts business on a nationwide basis.
(b) A player's obligation (pursuant to paragraph 13(e) of a Uniform Player Contract) to participate, upon request, in all other reasonable promotional activities of the Team and the Association shall be deemed satisfied if, during each year of the period covered by such Contract, the Player makes six individual personal appearances and six group appearances for or on behalf of or at the request of the Team (or Team Affiliate) by which he is employed and/or the NBA. Up to two of these twelve appearances may be assigned by the Team and/or the NBA in any year to NBA Properties. The Player shall be reimbursed for the actual expenses incurred in connection with any such appearance, provided that such expenses result directly from the appearance and are ordinary and reasonable. The Player shall also receive compensation from the Team by which he is employed of at least \$1,000, in accordance with paragraph 13(e) of the Uniform Player Contract, for each promotional appearance he makes for a commercial sponsor of such Team. Any personal or group appearance required under this subsection (b) must:
    (i) take place during (A) the period from the first day of a Season through the day of the NBA Draft following such Season, or (B) during the off-season, provided that no player may be required to make more than one off-season appearance in any year covered by his Contract and no player may be required to make such an off-season appearance unless he resides in or is otherwise located in the area where the appearance is to take place;
    (ii) occur in the home city (or geographic vicinity thereof) of the player's Team (subject to subsection (b)(i)(B) above) or in a city (or geographic vicinity thereof) to which the player has traveled to play in a scheduled NBA game;
    (iii) not occur at a time that would interfere with a player's reasonable preparation to play on the day of a Team game;
    (iv) not exceed a reasonable period of time; and
    (v) not require the player to sign autographs as the primary purpose of the appearance.

## Ten-Day Contracts.

(a) Beginning on January 5 (if a business day or the next succeeding business day) of any NBA Season, and solely for the purpose of replacing an injured player, a Team may enter into a Player Contract with a player, which Contract may, notwithstanding the provisions of paragraphs 7(c), 16(b), and 16(c) of the Uniform Player Contract, provide that such player will be compensated only for the period actually spent in the service of such Team. The duration of such Contract (a "lO-Day Contract") shall be limited to ten (10) days or a period encompassing three (3) games played by such Team, whichever is longer, and no Team may enter into such a Contract with the same player more than twice during the course of anyone Season.
(b) The Salary payable pursuant to a lO-Day Contract shall not be less than an amount calculated by multiplying the Minimum Annual Salary (as set forth in Article II, Sections 6(a) and (b)) for the NBA Season in which such Contract is executed by a fraction, the numerator of which is the number of days spent by such player in the service of such Team and the denominator of which is the total number of days of that NBA Regular Season.
(c) Notwithstanding anything to the contrary contained in a Uniform Player Contract, a lO-Day Contract may be terminated by written notice to the player and payment of only such sums as required by such Contract.

## Rest-of-Season Contracts.

(a) At any time after the start of an NBA Regular Season, a Team may enter into a Player Contract that may provide compensation to a player only for the remainder of that Season (a "Rest-of-Season Contract").
(b) The Salary payable pursuant to a Rest-of-Season Contract shall not be less than an amount calculated by multiplying the Minimum Annual Salary (as set forth in Article II, Sections 6(a) and (b)) for the NBA Season in which such Contract is executed by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season and the denominator of which is the total number of days of that NBA Regular Season.

## General.

(a) (i) Any oral or written agreement between a player and a Team concerning terms and conditions of employment shall be reduced to writing in the form of a Uniform Player Contract or an amendment thereto as soon as practicable. Immediately upon the consummation of any such agreement, the Team shall notify the NBA by facsimile or e-mail and provide the NBA with all economic terms of such agreement. As soon as practicable, but no later than three (3) business days following receipt of such notice by the NBA, the NBA shall provide the same notice to the Players Association.
    (ii) Notwithstanding subsection (a)(i) above, neither the NBA nor the Players Association shall contend that any agreement concerning terms and conditions of employment is binding upon the Player or the Team until a Player Contract embodying such terms and conditions has been duly executed by the parties. Nothing herein is intended to affect (A) any authority of the Commissioner to approve or disapprove Player Contracts, or (B) the effect of the Commissioner's approval or disapproval on the validity of such Player Contracts.
    (iii) A violation of the first sentence of subsection (a) (i) above may be considered evidence of a violation of Article XIII.
(b) No player shall attend the regular training camp of any Team, or participate in organized practices with the Team at any time, unless he is a party to a Player Contract then in effect. For purposes of this Section 10(b)), a player shall be considered to be a party to a Player Contract then in effect if such Contract has been extended in accordance with an option in favor of the Team or player permitted by this Agreement.
(c) No Team shall make any direct or indirect payment of any money, property, investments, loans, or anything else of value for fees or otherwise to an agent, attorney, or representative of a player (for or in connection with such person's representation of such player); nor shall any Player Contract provide for such payment. The foregoing shall not, however, prevent a Team from sending a player's regular paycheck to a player's agent, attorney, or representative if so instructed in writing by the player.