# PLAYER CONDUCT

## Fines and Suspensions.

In addition to any other rights a Team may have by Contract (including but not limited to the rights set forth in paragraph 9 of the Uniform Player Contract) or by law, when a player, without proper and reasonable cause, fails or refuses to render the services required by a Player Contract and/or when a player is, for proper cause, suspended by his Team or the NBA in accordance with the terms of such Contract, the Salary payable to the player for the year of the Contract during which such refusal or failure and/or suspension occurs may be reduced (or, in the case of a suspension, shall be reduced) as follows:

(a) By \$1,000 for each missed (training or Regular Season) day of practice (for the first two such missed practices), and by \$2,500 for each missed practice thereafter;
(b) By \$4,000 for each missed Exhibition Game;
(c) By 1/82nd of the player's Current Cash Compensation for each missed Regular Season or Playoff game;
(d) By \$1,000 for each missed promotional appearance required in accordance with Article II, Section 7(b) and paragraph 13 of the Uniform Player Contract;
(e) By \$10,000 for failing to attend the Rookie Transition Program; and
(f) By \$5,000 for failing to attend any other programs designated as mandatory by either the NBA or the Players Association (e.g., HIV and substance abuse education programs), the designation of which by either party shall be subject to approval by the other, which approval shall not be unreasonably withheld.

## Charitable Contributions.

If, pursuant to the terms of this Agreement, (a) any fine or suspension is imposed on a player, (b) such fine or suspension-related salary amount is paid to the League, and (c) the fine or suspension is not grieved by the player under the provisions of Article XXXI, then, beginning with the 1996-97 Season, the NBA shall remit fifty percent (50\%) of the Salary withheld (or payment received) as a result of the fine or suspension to the National Basketball Players Association Foundation (the "NBPA Foundation") or such other charitable organization selected by the Players Association that qualifies for treatment under Section 501(c)(3) of the Internal Revenue Code of 1986, as now in effect or as it may hereafter be amended (a "Section 501(c)(3) Organization"), and that is approved by the NBA (which approval shall not be unreasonably withheld) (both hereinafter, the "NBPA-Selected Charitable Organization"). The NBA shall remit the remaining fifty percent (50\%) of the withheld Salary to a Section 501(c)(3) organization selected by the NBA and approved by the Players Association, which approval shall not be unreasonably withheld. If the player files a timely Grievance under Article XXXI, the Salary withheld (or the payment received), including fifty percent (50\%) of any accrued interest, shall be contributed to charity in the manner set forth above only to the extent the player does not prevail in the Grievance. The remittances made by the NBA pursuant to this Section shall be made annually, fifteen (15) days following the end of the NBA Season during which the fine or suspension-related salary amount is received. For purposes of this Article and all other provisions of this Agreement, any money remitted or paid to the National Basketball Players Association Foundation by the NBA shall be used for charitable purposes only, and not, for example, for any salaries of Foundation employees or administrative expenses.